# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

name : Docker-CI
trigger:
  branches:
    include:
      - main

resources:
- repo: self

pool:
 name: MyPool

variables:
  ImageName: '$(Build.BuildId)'
  tag: $(Build.BuildId)

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build and push Docker image
    steps:
    - task: Docker@1
      displayName: Build the Docker image
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: Build an image
        dockerfile: '**/Dockerfile'
        imageName: $(ImageName)
        includeLatestTag: true
        useDefaultContext: false
        containerRegistry: $(dockerRegistryServiceConnection)
        buildContext: '.'
        tags: |
            $(tag)
    - task: Docker@1
      displayName: 'Push the Docker image to Dockerhub'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: push image
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
            $(tag)
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
